name: NotioAI
description: Hashnode Post-Publication LLM Toolkit
author: Sadra Yahyapour

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  method:
    description: LLM tools ("abstract-article", "simplify-article", "translate-article", "generate-questions")
    required: true

  path:
    default: transformed_articles/

  translate_to:
    description: Output translation lagnauge (used with "translate-article" method)
    default: English

  question_limit:
    description: The amount of questions (used with "generate-questions" method)
    default: 20

  include_answers:
    description: Whether including the question answers (used with "generate-questions" method)
    default: true

  hypermode_endpoint:
    description: The Hypermode API endpoint
    required: true

  hypermode_api_token:
    description: The Hypermode API token
    required: true
