name: NotioAI
description: Hashnode Post-Publication LLM Toolkit
author: Sadra Yahyapour

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  github_event_before:
    default: ${{ github.event.before }}

  github_event_after:
    default: ${{ github.event.after }}
