name: NotioAI
description: Hashnode Post-Publication LLM Toolkit
author: Sadra Yahyapour

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  github_event_before:
    default: ${{ github.event.before }}

  github_event_after:
    default: ${{ github.event.after }}

  method:
    description: LLM tools ("summarizeArticle", "concludeArticle")
    required: true

  path:
    default: transformed_articles/

  translate_to:
    description: Output translation lagnauge.

  temperature:
    description: A number between 0.0 and 2.0 that controls the sampling temperature.
    default: 0.2

  hypernode_endpoint:
    description: The Hypernode API endpoint
    required: true

  hypernode_api_token:
    description: The Hypernode API token
    required: true
