[project]
name = "notioai"
version = "0.0.1"
description = "Hashnode Post-Publication LLM Toolkit"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pyaction==0.8.2"]

[tool.setuptools.packages.find]
exclude = ["test*"]

[project.optional-dependencies]
cli = ["pyaction[cli]==0.8.2"]
